/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.widgets;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.widgets.CCParticipantInfo;
import io.swagger.client.model.widgets.DetailedWidgetParticipantSetInfo;
import io.swagger.client.model.widgets.SenderInfo;
import io.swagger.client.model.widgets.ShareParticipantInfo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WidgetMembersInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-11T15:50:01.583+05:30")
public class WidgetMembersInfo {
  @SerializedName("additionalParticipantSets")
  private List<DetailedWidgetParticipantSetInfo> additionalParticipantSets = null;

  @SerializedName("ccsInfo")
  private List<CCParticipantInfo> ccsInfo = null;

  @SerializedName("creatorInfo")
  private SenderInfo creatorInfo = null;

  @SerializedName("sharesInfo")
  private List<ShareParticipantInfo> sharesInfo = null;

  @SerializedName("widgetParticipantSet")
  private DetailedWidgetParticipantSetInfo widgetParticipantSet = null;

  public WidgetMembersInfo additionalParticipantSets(List<DetailedWidgetParticipantSetInfo> additionalParticipantSets) {
    this.additionalParticipantSets = additionalParticipantSets;
    return this;
  }

  public WidgetMembersInfo addAdditionalParticipantSetsItem(DetailedWidgetParticipantSetInfo additionalParticipantSetsItem) {
    if (this.additionalParticipantSets == null) {
      this.additionalParticipantSets = new ArrayList<DetailedWidgetParticipantSetInfo>();
    }
    this.additionalParticipantSets.add(additionalParticipantSetsItem);
    return this;
  }

   /**
   * Information about the widget additional participant Sets
   * @return additionalParticipantSets
  **/
  @ApiModelProperty(value = "Information about the widget additional participant Sets")
  public List<DetailedWidgetParticipantSetInfo> getAdditionalParticipantSets() {
    return additionalParticipantSets;
  }

  public void setAdditionalParticipantSets(List<DetailedWidgetParticipantSetInfo> additionalParticipantSets) {
    this.additionalParticipantSets = additionalParticipantSets;
  }

  public WidgetMembersInfo ccsInfo(List<CCParticipantInfo> ccsInfo) {
    this.ccsInfo = ccsInfo;
    return this;
  }

  public WidgetMembersInfo addCcsInfoItem(CCParticipantInfo ccsInfoItem) {
    if (this.ccsInfo == null) {
      this.ccsInfo = new ArrayList<CCParticipantInfo>();
    }
    this.ccsInfo.add(ccsInfoItem);
    return this;
  }

   /**
   * Information of CC participants of the widget.
   * @return ccsInfo
  **/
  @ApiModelProperty(value = "Information of CC participants of the widget.")
  public List<CCParticipantInfo> getCcsInfo() {
    return ccsInfo;
  }

  public void setCcsInfo(List<CCParticipantInfo> ccsInfo) {
    this.ccsInfo = ccsInfo;
  }

  public WidgetMembersInfo creatorInfo(SenderInfo creatorInfo) {
    this.creatorInfo = creatorInfo;
    return this;
  }

   /**
   * Information of the creator of the widget.
   * @return creatorInfo
  **/
  @ApiModelProperty(value = "Information of the creator of the widget.")
  public SenderInfo getCreatorInfo() {
    return creatorInfo;
  }

  public void setCreatorInfo(SenderInfo creatorInfo) {
    this.creatorInfo = creatorInfo;
  }

  public WidgetMembersInfo sharesInfo(List<ShareParticipantInfo> sharesInfo) {
    this.sharesInfo = sharesInfo;
    return this;
  }

  public WidgetMembersInfo addSharesInfoItem(ShareParticipantInfo sharesInfoItem) {
    if (this.sharesInfo == null) {
      this.sharesInfo = new ArrayList<ShareParticipantInfo>();
    }
    this.sharesInfo.add(sharesInfoItem);
    return this;
  }

   /**
   * Information of the participants with whom the widget has been shared.
   * @return sharesInfo
  **/
  @ApiModelProperty(value = "Information of the participants with whom the widget has been shared.")
  public List<ShareParticipantInfo> getSharesInfo() {
    return sharesInfo;
  }

  public void setSharesInfo(List<ShareParticipantInfo> sharesInfo) {
    this.sharesInfo = sharesInfo;
  }

  public WidgetMembersInfo widgetParticipantSet(DetailedWidgetParticipantSetInfo widgetParticipantSet) {
    this.widgetParticipantSet = widgetParticipantSet;
    return this;
  }

   /**
   * Information about the widget participant Set
   * @return widgetParticipantSet
  **/
  @ApiModelProperty(value = "Information about the widget participant Set")
  public DetailedWidgetParticipantSetInfo getWidgetParticipantSet() {
    return widgetParticipantSet;
  }

  public void setWidgetParticipantSet(DetailedWidgetParticipantSetInfo widgetParticipantSet) {
    this.widgetParticipantSet = widgetParticipantSet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WidgetMembersInfo widgetMembersInfo = (WidgetMembersInfo) o;
    return Objects.equals(this.additionalParticipantSets, widgetMembersInfo.additionalParticipantSets) &&
        Objects.equals(this.ccsInfo, widgetMembersInfo.ccsInfo) &&
        Objects.equals(this.creatorInfo, widgetMembersInfo.creatorInfo) &&
        Objects.equals(this.sharesInfo, widgetMembersInfo.sharesInfo) &&
        Objects.equals(this.widgetParticipantSet, widgetMembersInfo.widgetParticipantSet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalParticipantSets, ccsInfo, creatorInfo, sharesInfo, widgetParticipantSet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WidgetMembersInfo {\n");
    
    sb.append("    additionalParticipantSets: ").append(toIndentedString(additionalParticipantSets)).append("\n");
    sb.append("    ccsInfo: ").append(toIndentedString(ccsInfo)).append("\n");
    sb.append("    creatorInfo: ").append(toIndentedString(creatorInfo)).append("\n");
    sb.append("    sharesInfo: ").append(toIndentedString(sharesInfo)).append("\n");
    sb.append("    widgetParticipantSet: ").append(toIndentedString(widgetParticipantSet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

