/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.libraryDocuments;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Location information for form fields
 */
@ApiModel(description = "Location information for form fields")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T13:23:41.998+11:00")
public class FormFieldLocation {
  @SerializedName("pageNumber")
  private Integer pageNumber = null;

  @SerializedName("top")
  private Double top = null;

  @SerializedName("left")
  private Double left = null;

  @SerializedName("width")
  private Double width = null;

  @SerializedName("height")
  private Double height = null;

  public FormFieldLocation pageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
    return this;
  }

   /**
   * Number of the page where form field has to be placed, starting from 1.
   * @return pageNumber
  **/
  @ApiModelProperty(value = "Number of the page where form field has to be placed, starting from 1.")
  public Integer getPageNumber() {
    return pageNumber;
  }

  public void setPageNumber(Integer pageNumber) {
    this.pageNumber = pageNumber;
  }

  public FormFieldLocation top(Double top) {
    this.top = top;
    return this;
  }

   /**
   * No. of pixels from bottom of the page for form field placement
   * @return top
  **/
  @ApiModelProperty(value = "No. of pixels from bottom of the page for form field placement")
  public Double getTop() {
    return top;
  }

  public void setTop(Double top) {
    this.top = top;
  }

  public FormFieldLocation left(Double left) {
    this.left = left;
    return this;
  }

   /**
   * No. of pixels from left of the page for form field placement
   * @return left
  **/
  @ApiModelProperty(value = "No. of pixels from left of the page for form field placement")
  public Double getLeft() {
    return left;
  }

  public void setLeft(Double left) {
    this.left = left;
  }

  public FormFieldLocation width(Double width) {
    this.width = width;
    return this;
  }

   /**
   * Width of the form field in pixels
   * @return width
  **/
  @ApiModelProperty(value = "Width of the form field in pixels")
  public Double getWidth() {
    return width;
  }

  public void setWidth(Double width) {
    this.width = width;
  }

  public FormFieldLocation height(Double height) {
    this.height = height;
    return this;
  }

   /**
   * Height of the form field in pixels
   * @return height
  **/
  @ApiModelProperty(value = "Height of the form field in pixels")
  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormFieldLocation formFieldLocation = (FormFieldLocation) o;
    return Objects.equals(this.pageNumber, formFieldLocation.pageNumber) &&
        Objects.equals(this.top, formFieldLocation.top) &&
        Objects.equals(this.left, formFieldLocation.left) &&
        Objects.equals(this.width, formFieldLocation.width) &&
        Objects.equals(this.height, formFieldLocation.height);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageNumber, top, left, width, height);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormFieldLocation {\n");
    
    sb.append("    pageNumber: ").append(toIndentedString(pageNumber)).append("\n");
    sb.append("    top: ").append(toIndentedString(top)).append("\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

