/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.libraryDocuments;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.libraryDocuments.LibraryDocumentEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LibraryDocumentEventList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-11T15:49:09.941+05:30")
public class LibraryDocumentEventList {
  @SerializedName("events")
  private List<LibraryDocumentEvent> events = null;

  public LibraryDocumentEventList events(List<LibraryDocumentEvent> events) {
    this.events = events;
    return this;
  }

  public LibraryDocumentEventList addEventsItem(LibraryDocumentEvent eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<LibraryDocumentEvent>();
    }
    this.events.add(eventsItem);
    return this;
  }

   /**
   * An array of event objects.
   * @return events
  **/
  @ApiModelProperty(value = "An array of event objects.")
  public List<LibraryDocumentEvent> getEvents() {
    return events;
  }

  public void setEvents(List<LibraryDocumentEvent> events) {
    this.events = events;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LibraryDocumentEventList libraryDocumentEventList = (LibraryDocumentEventList) o;
    return Objects.equals(this.events, libraryDocumentEventList.events);
  }

  @Override
  public int hashCode() {
    return Objects.hash(events);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LibraryDocumentEventList {\n");
    
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

