/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.accounts;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;

/**
 * Account resource for the User
 */
@ApiModel(description = "Account resource for the User")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T13:23:33.105+11:00")
public class Account {
  @SerializedName("created")
  private Date created = null;

  /**
   * The provisioned type of the account. This is a server generated attributed and can not be provided in POST/PUT calls.
   */
  @JsonAdapter(AccountTypeEnum.Adapter.class)
  public enum AccountTypeEnum {
    FREE("FREE"),
    
    FREE_LEGACY("FREE_LEGACY"),
    
    TEAM_TRIAL("TEAM_TRIAL"),
    
    TEAM("TEAM"),
    
    TEAM_LEGACY("TEAM_LEGACY"),
    
    ENTERPRISE_TRIAL("ENTERPRISE_TRIAL"),
    
    ENTERPRISE("ENTERPRISE"),
    
    ENTERPRISE_LEGACY("ENTERPRISE_LEGACY"),
    
    GLOBAL_TRIAL("GLOBAL_TRIAL"),
    
    GLOBAL("GLOBAL"),
    
    DEVELOPER("DEVELOPER"),
    
    PRO_DOC_CLOUD("PRO_DOC_CLOUD"),
    
    TEAM_DOC_CLOUD("TEAM_DOC_CLOUD"),
    
    TRIAL_EXPIRED("TRIAL_EXPIRED"),
    
    ANONYMOUS("ANONYMOUS"),
    
    PRO_DOC_CLOUD_MULTI("PRO_DOC_CLOUD_MULTI"),
    
    PRO_PLUS_DOC_CLOUD("PRO_PLUS_DOC_CLOUD"),
    
    PRO_PLUS_DOC_CLOUD_MULTI("PRO_PLUS_DOC_CLOUD_MULTI");

    private String value;

    AccountTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AccountTypeEnum fromValue(String text) {
      for (AccountTypeEnum b : AccountTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AccountTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AccountTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AccountTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AccountTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("accountType")
  private AccountTypeEnum accountType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("modified")
  private Date modified = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("id")
  private String id = null;

  public Account created(Date created) {
    this.created = created;
    return this;
  }

   /**
   * Date when the account was created. This is a server generated attributed and can not be provided in POST/PUT calls. Format would be yyyy-MM-dd&#39;T&#39;HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
   * @return created
  **/
  @ApiModelProperty(value = "Date when the account was created. This is a server generated attributed and can not be provided in POST/PUT calls. Format would be yyyy-MM-dd'T'HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time")
  public Date getCreated() {
    return created;
  }

  public void setCreated(Date created) {
    this.created = created;
  }

  public Account accountType(AccountTypeEnum accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * The provisioned type of the account. This is a server generated attributed and can not be provided in POST/PUT calls.
   * @return accountType
  **/
  @ApiModelProperty(value = "The provisioned type of the account. This is a server generated attributed and can not be provided in POST/PUT calls.")
  public AccountTypeEnum getAccountType() {
    return accountType;
  }

  public void setAccountType(AccountTypeEnum accountType) {
    this.accountType = accountType;
  }

  public Account name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name which the account is known. This is a server generated attributed and can not be provided in POST/PUT calls. 
   * @return name
  **/
  @ApiModelProperty(value = "The name which the account is known. This is a server generated attributed and can not be provided in POST/PUT calls. ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Account modified(Date modified) {
    this.modified = modified;
    return this;
  }

   /**
   * The last date that the account information was updated. This is a server generated attributed and can not be provided in POST/PUT calls. Format would be yyyy-MM-dd&#39;T&#39;HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time
   * @return modified
  **/
  @ApiModelProperty(value = "The last date that the account information was updated. This is a server generated attributed and can not be provided in POST/PUT calls. Format would be yyyy-MM-dd'T'HH:mm:ssZ. For example, e.g 2016-02-25T18:46:19Z represents UTC time")
  public Date getModified() {
    return modified;
  }

  public void setModified(Date modified) {
    this.modified = modified;
  }

  public Account company(String company) {
    this.company = company;
    return this;
  }

   /**
   * The company associated with the account. This is a server generated attributed and can not be provided in POST/PUT calls. 
   * @return company
  **/
  @ApiModelProperty(value = "The company associated with the account. This is a server generated attributed and can not be provided in POST/PUT calls. ")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public Account id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier of the account. This is a server generated attributed and can not be provided in POST/PUT calls. 
   * @return id
  **/
  @ApiModelProperty(value = "Identifier of the account. This is a server generated attributed and can not be provided in POST/PUT calls. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.created, account.created) &&
        Objects.equals(this.accountType, account.accountType) &&
        Objects.equals(this.name, account.name) &&
        Objects.equals(this.modified, account.modified) &&
        Objects.equals(this.company, account.company) &&
        Objects.equals(this.id, account.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, accountType, name, modified, company, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

