/**
*  Copyright 2019 Adobe Systems Incorporated. All rights reserved.
*  This file is licensed to you under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License. You may obtain a copy
*  of the License at http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software distributed under
*  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
*  OF ANY KIND, either express or implied. See the License for the specific language
*  governing permissions and limitations under the License.
*
*
**/


/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.agreements;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.agreements.PageInfo;
import io.swagger.client.model.agreements.UserAgreement;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UserAgreements
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-11T15:48:52.659+05:30")
public class UserAgreements {
  @SerializedName("page")
  private PageInfo page = null;

  @SerializedName("userAgreementList")
  private List<UserAgreement> userAgreementList = null;

  public UserAgreements page(PageInfo page) {
    this.page = page;
    return this;
  }

   /**
   * Pagination information for navigating through the response
   * @return page
  **/
  @ApiModelProperty(value = "Pagination information for navigating through the response")
  public PageInfo getPage() {
    return page;
  }

  public void setPage(PageInfo page) {
    this.page = page;
  }

  public UserAgreements userAgreementList(List<UserAgreement> userAgreementList) {
    this.userAgreementList = userAgreementList;
    return this;
  }

  public UserAgreements addUserAgreementListItem(UserAgreement userAgreementListItem) {
    if (this.userAgreementList == null) {
      this.userAgreementList = new ArrayList<UserAgreement>();
    }
    this.userAgreementList.add(userAgreementListItem);
    return this;
  }

   /**
   * An array of UserAgreement items
   * @return userAgreementList
  **/
  @ApiModelProperty(value = "An array of UserAgreement items")
  public List<UserAgreement> getUserAgreementList() {
    return userAgreementList;
  }

  public void setUserAgreementList(List<UserAgreement> userAgreementList) {
    this.userAgreementList = userAgreementList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserAgreements userAgreements = (UserAgreements) o;
    return Objects.equals(this.page, userAgreements.page) &&
        Objects.equals(this.userAgreementList, userAgreements.userAgreementList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(page, userAgreementList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserAgreements {\n");
    
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    userAgreementList: ").append(toIndentedString(userAgreementList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

