/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FileUploadOptions;
import java.io.IOException;

/**
 * ComposeViewConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-06T11:30:55.372+05:30")
public class ComposeViewConfiguration {
  @SerializedName("fileUploadOptions")
  private FileUploadOptions fileUploadOptions = null;

  @SerializedName("isPreviewSelected")
  private Boolean isPreviewSelected = null;

  public ComposeViewConfiguration fileUploadOptions(FileUploadOptions fileUploadOptions) {
    this.fileUploadOptions = fileUploadOptions;
    return this;
  }

   /**
   * Controls various file upload options available on the send page
   * @return fileUploadOptions
  **/
  @ApiModelProperty(value = "Controls various file upload options available on the send page")
  public FileUploadOptions getFileUploadOptions() {
    return fileUploadOptions;
  }

  public void setFileUploadOptions(FileUploadOptions fileUploadOptions) {
    this.fileUploadOptions = fileUploadOptions;
  }

  public ComposeViewConfiguration isPreviewSelected(Boolean isPreviewSelected) {
    this.isPreviewSelected = isPreviewSelected;
    return this;
  }

   /**
   * Should the COMPOSE page be provided with authoring mode selected?
   * @return isPreviewSelected
  **/
  @ApiModelProperty(value = "Should the COMPOSE page be provided with authoring mode selected?")
  public Boolean isIsPreviewSelected() {
    return isPreviewSelected;
  }

  public void setIsPreviewSelected(Boolean isPreviewSelected) {
    this.isPreviewSelected = isPreviewSelected;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComposeViewConfiguration composeViewConfiguration = (ComposeViewConfiguration) o;
    return Objects.equals(this.fileUploadOptions, composeViewConfiguration.fileUploadOptions) &&
        Objects.equals(this.isPreviewSelected, composeViewConfiguration.isPreviewSelected);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileUploadOptions, isPreviewSelected);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComposeViewConfiguration {\n");
    
    sb.append("    fileUploadOptions: ").append(toIndentedString(fileUploadOptions)).append("\n");
    sb.append("    isPreviewSelected: ").append(toIndentedString(isPreviewSelected)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

