/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CommonViewConfiguration;
import java.io.IOException;

/**
 * LibraryViewInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-06T11:31:19.178+05:30")
public class LibraryViewInfo {
  @SerializedName("commonViewConfiguration")
  private CommonViewConfiguration commonViewConfiguration = null;

  /**
   * Name of the requested libraryDocument view
   */
  @JsonAdapter(NameEnum.Adapter.class)
  public enum NameEnum {
    EDIT("EDIT"),
    
    DOCUMENT("DOCUMENT"),
    
    MANAGE("MANAGE"),
    
    SEND("SEND"),
    
    ALL("ALL");

    private String value;

    NameEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NameEnum fromValue(String text) {
      for (NameEnum b : NameEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<NameEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NameEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NameEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return NameEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("name")
  private NameEnum name = null;

  public LibraryViewInfo commonViewConfiguration(CommonViewConfiguration commonViewConfiguration) {
    this.commonViewConfiguration = commonViewConfiguration;
    return this;
  }

   /**
   * Common view configuration for all the available views
   * @return commonViewConfiguration
  **/
  @ApiModelProperty(value = "Common view configuration for all the available views")
  public CommonViewConfiguration getCommonViewConfiguration() {
    return commonViewConfiguration;
  }

  public void setCommonViewConfiguration(CommonViewConfiguration commonViewConfiguration) {
    this.commonViewConfiguration = commonViewConfiguration;
  }

  public LibraryViewInfo name(NameEnum name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the requested libraryDocument view
   * @return name
  **/
  @ApiModelProperty(value = "Name of the requested libraryDocument view")
  public NameEnum getName() {
    return name;
  }

  public void setName(NameEnum name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LibraryViewInfo libraryViewInfo = (LibraryViewInfo) o;
    return Objects.equals(this.commonViewConfiguration, libraryViewInfo.commonViewConfiguration) &&
        Objects.equals(this.name, libraryViewInfo.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonViewConfiguration, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LibraryViewInfo {\n");
    
    sb.append("    commonViewConfiguration: ").append(toIndentedString(commonViewConfiguration)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

