/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SenderInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-06T11:31:50.276+05:30")
public class SenderInfo {
  @SerializedName("company")
  private String company = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("participantId")
  private String participantId = null;

  @SerializedName("self")
  private Boolean self = null;

  public SenderInfo company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Company of the creator, if available.
   * @return company
  **/
  @ApiModelProperty(value = "Company of the creator, if available.")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public SenderInfo email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email of the creator of the widget.
   * @return email
  **/
  @ApiModelProperty(value = "Email of the creator of the widget.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public SenderInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the creator, if available.
   * @return name
  **/
  @ApiModelProperty(value = "Name of the creator, if available.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SenderInfo participantId(String participantId) {
    this.participantId = participantId;
    return this;
  }

   /**
   *  The unique identifier of the creator of the widget.
   * @return participantId
  **/
  @ApiModelProperty(value = " The unique identifier of the creator of the widget.")
  public String getParticipantId() {
    return participantId;
  }

  public void setParticipantId(String participantId) {
    this.participantId = participantId;
  }

  public SenderInfo self(Boolean self) {
    this.self = self;
    return this;
  }

   /**
   * True if the creator of the widget is the same user that is calling the API.
   * @return self
  **/
  @ApiModelProperty(value = "True if the creator of the widget is the same user that is calling the API.")
  public Boolean isSelf() {
    return self;
  }

  public void setSelf(Boolean self) {
    this.self = self;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SenderInfo senderInfo = (SenderInfo) o;
    return Objects.equals(this.company, senderInfo.company) &&
        Objects.equals(this.email, senderInfo.email) &&
        Objects.equals(this.name, senderInfo.name) &&
        Objects.equals(this.participantId, senderInfo.participantId) &&
        Objects.equals(this.self, senderInfo.self);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, email, name, participantId, self);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SenderInfo {\n");
    
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    participantId: ").append(toIndentedString(participantId)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

