/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.users;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.users.PageInfo;
import io.swagger.client.model.users.UserInfo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UsersInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T13:23:51.296+11:00")
public class UsersInfo {
  @SerializedName("userInfoList")
  private List<UserInfo> userInfoList = null;

  @SerializedName("page")
  private PageInfo page = null;

  public UsersInfo userInfoList(List<UserInfo> userInfoList) {
    this.userInfoList = userInfoList;
    return this;
  }

  public UsersInfo addUserInfoListItem(UserInfo userInfoListItem) {
    if (this.userInfoList == null) {
      this.userInfoList = new ArrayList<UserInfo>();
    }
    this.userInfoList.add(userInfoListItem);
    return this;
  }

   /**
   * The list of users in the account.
   * @return userInfoList
  **/
  @ApiModelProperty(value = "The list of users in the account.")
  public List<UserInfo> getUserInfoList() {
    return userInfoList;
  }

  public void setUserInfoList(List<UserInfo> userInfoList) {
    this.userInfoList = userInfoList;
  }

  public UsersInfo page(PageInfo page) {
    this.page = page;
    return this;
  }

   /**
   * Pagination information for navigating through the response
   * @return page
  **/
  @ApiModelProperty(value = "Pagination information for navigating through the response")
  public PageInfo getPage() {
    return page;
  }

  public void setPage(PageInfo page) {
    this.page = page;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsersInfo usersInfo = (UsersInfo) o;
    return Objects.equals(this.userInfoList, usersInfo.userInfoList) &&
        Objects.equals(this.page, usersInfo.page);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userInfoList, page);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsersInfo {\n");
    
    sb.append("    userInfoList: ").append(toIndentedString(userInfoList)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

