/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.workflows;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MergeFieldInfoDescription
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T13:23:59.041+11:00")
public class MergeFieldInfoDescription {
  @SerializedName("fieldName")
  private String fieldName = null;

  @SerializedName("visible")
  private Boolean visible = null;

  @SerializedName("defaultValue")
  private String defaultValue = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("editable")
  private Boolean editable = null;

  @SerializedName("required")
  private Boolean required = null;

  public MergeFieldInfoDescription fieldName(String fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Name of the custom field in this workflow
   * @return fieldName
  **/
  @ApiModelProperty(value = "Name of the custom field in this workflow")
  public String getFieldName() {
    return fieldName;
  }

  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

  public MergeFieldInfoDescription visible(Boolean visible) {
    this.visible = visible;
    return this;
  }

   /**
   * Whether current field should be visible on agreement creation page. If visible attribute for this field is false then this field should not be shown on the agreement creation page using this workflow
   * @return visible
  **/
  @ApiModelProperty(value = "Whether current field should be visible on agreement creation page. If visible attribute for this field is false then this field should not be shown on the agreement creation page using this workflow")
  public Boolean isVisible() {
    return visible;
  }

  public void setVisible(Boolean visible) {
    this.visible = visible;
  }

  public MergeFieldInfoDescription defaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * default value of the field if input for this field is not provided and this field is required
   * @return defaultValue
  **/
  @ApiModelProperty(value = "default value of the field if input for this field is not provided and this field is required")
  public String getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public MergeFieldInfoDescription displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display text that can be shown for this custom field
   * @return displayName
  **/
  @ApiModelProperty(value = "The display text that can be shown for this custom field")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MergeFieldInfoDescription editable(Boolean editable) {
    this.editable = editable;
    return this;
  }

   /**
   * Whether current field can be edited. If editable attribute for this field is false then this field should not be provided in the agreement creation request and default value of this field will be used in agreement creation
   * @return editable
  **/
  @ApiModelProperty(value = "Whether current field can be edited. If editable attribute for this field is false then this field should not be provided in the agreement creation request and default value of this field will be used in agreement creation")
  public Boolean isEditable() {
    return editable;
  }

  public void setEditable(Boolean editable) {
    this.editable = editable;
  }

  public MergeFieldInfoDescription required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * Whether this field is required or optional
   * @return required
  **/
  @ApiModelProperty(value = "Whether this field is required or optional")
  public Boolean isRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergeFieldInfoDescription mergeFieldInfoDescription = (MergeFieldInfoDescription) o;
    return Objects.equals(this.fieldName, mergeFieldInfoDescription.fieldName) &&
        Objects.equals(this.visible, mergeFieldInfoDescription.visible) &&
        Objects.equals(this.defaultValue, mergeFieldInfoDescription.defaultValue) &&
        Objects.equals(this.displayName, mergeFieldInfoDescription.displayName) &&
        Objects.equals(this.editable, mergeFieldInfoDescription.editable) &&
        Objects.equals(this.required, mergeFieldInfoDescription.required);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldName, visible, defaultValue, displayName, editable, required);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergeFieldInfoDescription {\n");
    
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    visible: ").append(toIndentedString(visible)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

