/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model.workflows;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.workflows.UserWorkflow;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UserWorkflows
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-06T13:23:59.041+11:00")
public class UserWorkflows {
  @SerializedName("userWorkflowList")
  private List<UserWorkflow> userWorkflowList = null;

  public UserWorkflows userWorkflowList(List<UserWorkflow> userWorkflowList) {
    this.userWorkflowList = userWorkflowList;
    return this;
  }

  public UserWorkflows addUserWorkflowListItem(UserWorkflow userWorkflowListItem) {
    if (this.userWorkflowList == null) {
      this.userWorkflowList = new ArrayList<UserWorkflow>();
    }
    this.userWorkflowList.add(userWorkflowListItem);
    return this;
  }

   /**
   * An array of workflows
   * @return userWorkflowList
  **/
  @ApiModelProperty(value = "An array of workflows")
  public List<UserWorkflow> getUserWorkflowList() {
    return userWorkflowList;
  }

  public void setUserWorkflowList(List<UserWorkflow> userWorkflowList) {
    this.userWorkflowList = userWorkflowList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWorkflows userWorkflows = (UserWorkflows) o;
    return Objects.equals(this.userWorkflowList, userWorkflows.userWorkflowList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userWorkflowList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWorkflows {\n");
    
    sb.append("    userWorkflowList: ").append(toIndentedString(userWorkflowList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

